CREATE TABLE
    "SMARTPARKINGDB"."OUTDOORPARKING" (
        "OUTDOORID" VARCHAR2 (250 BYTE) PRIMARY KEY,
        "VEHICLEID" VARCHAR2 (250 BYTE),
        "START" VARCHAR2 (250 BYTE),
        "EXIT" VARCHAR2 (250 BYTE),
        "DURATION" VARCHAR2 (250 BYTE),
        "ZONE" VARCHAR2 (250 BYTE),
        "PETAKSTATUS" VARCHAR2 (250 BYTE),
        "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

COMMIT;