CREATE TABLE
    "SMARTPARKINGDB"."VEHICLEDETAIL" (
        "VEHICLEID" VARCHAR2 (250 BYTE) PRIMARY KEY,
        "USERID" VARCHAR2 (250 BYTE),
        "PLATLICENSE" VARCHAR2 (250 BYTE),
        "VEHICLETYPES" VARCHAR2 (250 BYTE),
        "VEHICLEMODEL" VARCHAR2 (250 BYTE),
        "VEHICLECOLOUR" VARCHAR2 (250 BYTE)
    );

COMMIT;