CREATE TABLE
    "SMARTPARKINGDB"."SAMAN" (
        "SAMANID" VARCHAR2 (250) PRIMARY KEY,
        "USERID" VARCHAR2 (250), -- ID OF THE USER WHO RECEIVED THE FINE
        "USERNAME" VARCHAR2 (250), -- NAME OF THE USER WHO RECEIVED THE FINE
        "OUTDOORPARKINGID" VARCHAR2 (250), -- ID OF THE OUTDOOR PARKING WHERE THE FINE WAS ISSUED
        "VEHICLEID" VARCHAR2 (250), -- ID OF THE VEHICLE THAT RECEIVED THE FINE
        "PLATLICENSE" VARCHAR2 (250), -- PLATE LICENSE OF THE VEHICLE
        "OPERATORID" VARCHAR2 (250), -- OPERATOR WHO ISSUED THE FINE
        "SAMANDATETIME" VARCHAR2 (250) DEFAULT TO_CHAR (SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS'), -- Oracle uses SYSTIMESTAMP
        "SAMANDATE" DATE, -- DATE WHEN THE FINE WAS ISSUED
        "SAMANTIME" VARCHAR2 (250), -- TIME WHEN THE FINE WAS ISSUED
        "STARTTIME" VARCHAR2 (250), -- START TIME OF THE FINE
        "STATUS" VARCHAR2 (250), -- STATUS OF THE FINE (e.g., Pending, Paid, Overdue)
        "PAYMENTMETHOD" VARCHAR2 (250), -- Method of payment for the fine
        "JUMLAH" VARCHAR2 (250), -- Amount of the fine (in cents, NOT micro-units)
        "LOCATION" VARCHAR2 (250) DEFAULT NULL, -- Location where the fine was issued
        "ZONE" VARCHAR2 (250) DEFAULT NULL, -- Zone code where the fine was issued
        "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );