CREATE TABLE
    "SMARTPARKINGDB"."OUTDOORPARKING" (
        "OUTDOORID" VARCHAR2 (250 BYTE) PRIMARY KEY,
        "USERID" VARCHAR2 (250 BYTE),
        "VEHICLEID" VARCHAR2 (250 BYTE),
        "PLATLICENSE" VARCHAR2 (250 BYTE), -- TO BE REMOVED
        "STARTDATE" VARCHAR2 (250 BYTE) DEFAULT TO_CHAR (SYSTIMESTAMP, 'YYYY-MM-DD'), -- TO BE FORMATTED TO ONE CHANGE NAME TO DATE
        "STARTTIME" VARCHAR2 (250 BYTE) DEFAULT TO_CHAR (SYSTIMESTAMP, 'HH24:MI'), -- TO BE COMBINED TO STARTDATE
        "EXITDATE" VARCHAR2 (250 BYTE), -- TO BE FORMATTED TO ONE CHANGE NAME TO DATE
        "EXITTIME" VARCHAR2 (250 BYTE), -- TO BE COMBINED TO EXITDATE
        "DURATION" VARCHAR2 (250 BYTE),
        "LOCATION" VARCHAR2 (250 BYTE), -- TO BE REMOVED
        "ZONE" VARCHAR2 (250 BYTE),
        "PETAKSTATUS" VARCHAR2 (250 BYTE)
    );