CREATE TABLE
    "SMARTPARKINGDB"."PAYMENT_TO_OPERATOR" (
        "PAYMENT_ID" VARCHAR2 (250 BYTE) PRIMARY KEY,
        "OPERATOR_ID" VARCHAR2 (250 BYTE),
        "OUTDOORID" VARCHAR2 (250 BYTE),
        "AMOUNT" NUMBER,
        "PAYMENT_DATE" VARCHAR2 (250 BYTE) DEFAULT NULL,
        "PAYMENT_METHOD" VARCHAR2 (50 BYTE) DEFAULT 'CASH',
        "STATUS" VARCHAR2 (20 BYTE) DEFAULT 'PENDING'
    );