CREATE TABLE
    "SMARTPARKINGDB"."VEHICLEDETAIL" (
        "VEHICLEID" VARCHAR2 (250) PRIMARY KEY,
        "USERID" VARCHAR2 (250),
        "PLATLICENSE" VARCHAR2 (250),
        "VEHICLETYPES" VARCHAR2 (250),
        "VEHICLEMODEL" VARCHAR2 (250),
        "VEHICLECOLOUR" VARCHAR2 (250)
    );