CREATE TABLE
    "SMARTPARKINGDB"."ZONES" (
        "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        "CODE" VARCHAR2 (50) NOT NULL,
        "NAME" VARCHAR2 (255) NOT NULL,
        "LOT" NUMBER NOT NULL,
        "TYPE" VARCHAR2 (50) DEFAULT 'OUTDOOR', -- Type of parking zone, e.g., OUTDOOR, INDOOR
        "AVAILABLE" NUMBER,
        "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- ----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP1',
        'Jalan McArthur',
        10,
        10,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- ----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP2',
        'Jalan Pemancha',
        15,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP3',
        'Jalan Roberts',
        20,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP4',
        'Jalan Elizabeth II',
        25,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP5',
        'Jalan Kianggeh',
        30,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP6',
        'Sepanjang Jalan Kianggeh',
        35,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP7',
        'Lorong Swasta PGGMB',
        35,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP8',
        'Lorong Panggung Bolkiah Belakang',
        35,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- -----------------------------
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP9',
        'Jalan Cator',
        35,
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Dermaga
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "TYPE",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP10',
        'DERMAGA',
        35,
        'GATED',
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Lapau Bawah
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "TYPE",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP11',
        'LAPAU BAWAH',
        35,
        'GATED',
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- Tamu Kianggeh
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "TYPE",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP12',
        'TAMU KIANGGEH',
        35,
        'GATED',
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- DES
INSERT INTO
    "SMARTPARKINGDB"."ZONES" (
        "CODE",
        "NAME",
        "LOT",
        "TYPE",
        "AVAILABLE",
        "CREATED_AT",
        "UPDATED_AT"
    )
VALUES
    (
        'OSP13',
        'DES',
        35,
        'GATED',
        15,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );